#!/usr/bin/env bash
set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────
PYTHON="${PYTHON:-python3}"
SIM_DIR="${SIM_DIR:-$(cd "$(dirname "$0")" && pwd)}"
RULES="$SIM_DIR/outputs/Static files/rule_database.csv"
SIMULATOR_YAML="$SIM_DIR/simulator.yaml"
SEED=2025

# Output base directories
NR_BASE="$SIM_DIR/outputs/noregen_runs"
RG_BASE="$SIM_DIR/outputs/regen_runs"

# Topology source directories
NR_TOPO_SRC="$SIM_DIR/outputs/topology_preview_noregen"
RG_TOPO_SRC="$SIM_DIR/outputs/topology_preview_regen"

# ── Step 0: Ensure topology preview dirs exist ─────────────────────────────
if [ ! -f "$NR_TOPO_SRC/board.graphml" ]; then
  echo "==> Generating noregen topology..."
  cd "$SIM_DIR"
  ARANGO_SKIP=1 REGEN_HOPS=0 TOPO_PREVIEW_DIR="$NR_TOPO_SRC" $PYTHON run.py
fi

if [ ! -f "$RG_TOPO_SRC/board.graphml" ]; then
  echo "==> Generating regen topology..."
  cd "$SIM_DIR"
  ARANGO_SKIP=1 REGEN_HOPS=2 TOPO_PREVIEW_DIR="$RG_TOPO_SRC" $PYTHON run.py
fi

# ── Step 1: Convert GraphML to topology YAML ──────────────────────────────
mkdir -p "$NR_BASE" "$RG_BASE"

NR_TOPO_YAML="$NR_BASE/topology_noregen.yaml"
NR_ROLES_YAML="$NR_BASE/roles_noregen.yaml"
RG_TOPO_YAML="$RG_BASE/topology_regen.yaml"
RG_ROLES_YAML="$RG_BASE/roles_regen.yaml"

if [ ! -f "$NR_TOPO_YAML" ]; then
  echo "==> Converting noregen GraphML -> topology YAML..."
  $PYTHON "$SIM_DIR/convert_graphml_to_topology.py" \
    --graphml "$NR_TOPO_SRC/board.graphml" \
    --lightpaths "$NR_TOPO_SRC/lightpaths.txt" \
    --out "$NR_TOPO_YAML" \
    --regen-hops 0
fi

# For regen, use board_regen.graphml if available, else board.graphml
RG_GRAPHML="$RG_TOPO_SRC/board_regen.graphml"
if [ ! -f "$RG_GRAPHML" ]; then
  RG_GRAPHML="$RG_TOPO_SRC/board.graphml"
fi

if [ ! -f "$RG_TOPO_YAML" ]; then
  echo "==> Converting regen GraphML -> topology YAML..."
  $PYTHON "$SIM_DIR/convert_graphml_to_topology.py" \
    --graphml "$RG_GRAPHML" \
    --lightpaths "$RG_TOPO_SRC/lightpaths.txt" \
    --out "$RG_TOPO_YAML" \
    --regen-hops 2
fi

# Check if roles files exist (generated by convert script)
if [ ! -f "$NR_ROLES_YAML" ]; then
  # Fallback: use the global roles.yaml
  NR_ROLES_YAML="$SIM_DIR/roles.yaml"
fi
if [ ! -f "$RG_ROLES_YAML" ]; then
  RG_ROLES_YAML="$SIM_DIR/roles.yaml"
fi

# ── Step 2: Topology graph plots ──────────────────────────────────────────
echo ""
echo "============================================"
echo "  Generating topology plots..."
echo "============================================"

$PYTHON "$SIM_DIR/plot_topology_graph.py" \
  --graphml "$NR_TOPO_SRC/board.graphml" \
  --out "$NR_BASE/topology_graph.png" \
  --mode board --labels 2>/dev/null || echo "  (noregen topology plot skipped)"

$PYTHON "$SIM_DIR/plot_topology_graph.py" \
  --graphml "$RG_GRAPHML" \
  --out "$RG_BASE/topology_graph.png" \
  --mode board --labels 2>/dev/null || echo "  (regen topology plot skipped)"

# ── Step 3: Run all failure types ─────────────────────────────────────────

run_event() {
  local MODE="$1"       # noregen or regen
  local EVENT="$2"
  local BOARD="$3"
  local ROLE="$4"
  local SEV="$5"

  if [ "$MODE" = "noregen" ]; then
    local BASE_DIR="$NR_BASE"
    local TOPO_YAML="$NR_TOPO_YAML"
    local ROLES_YAML="$NR_ROLES_YAML"
    local LIGHTPATHS="$NR_TOPO_SRC/lightpaths.txt"
  else
    local BASE_DIR="$RG_BASE"
    local TOPO_YAML="$RG_TOPO_YAML"
    local ROLES_YAML="$RG_ROLES_YAML"
    local LIGHTPATHS="$RG_TOPO_SRC/lightpaths.txt"
  fi

  local EVENT_LOWER
  EVENT_LOWER=$(echo "$EVENT" | tr '[:upper:]' '[:lower:]')
  local RUN_DIR="$BASE_DIR/$EVENT"
  local DATA_DIR="$BASE_DIR/data_outputs_${EVENT_LOWER}"

  # Skip if alarm_flow.csv already exists
  if [ -f "$RUN_DIR/alarm_flow.csv" ] && [ -f "$DATA_DIR/Node_1" ]; then
    echo "  [SKIP] $MODE / $EVENT (already exists)"
  else
    echo ""
    echo "============================================"
    echo "  Running: $EVENT ($MODE)"
    echo "============================================"

    mkdir -p "$RUN_DIR" "$DATA_DIR"

    # Create failure.csv
    printf 'Board,Event,Severity,Time,DurationMs,BoardRole\n%s,%s,%s,2025-10-26 00:00:42,60000,%s\n' \
      "$BOARD" "$EVENT" "$SEV" "$ROLE" > "$RUN_DIR/failure.csv"

    echo "  [1/2] Running simulator..."
    $PYTHON "$SIM_DIR/otn_simulator.py" \
      --topology "$TOPO_YAML" \
      --roles "$ROLES_YAML" \
      --simulator "$SIMULATOR_YAML" \
      --outdir "$DATA_DIR" \
      --failures "$RUN_DIR/failure.csv" \
      --alarm-flow \
      --alarm-outdir "$RUN_DIR" \
      --alarm-rules "$RULES" \
      --alarm-spikes-from-flow \
      --paths-from "$LIGHTPATHS" \
      --seed $SEED

    # Copy lightpaths to run dir
    cp "$LIGHTPATHS" "$RUN_DIR/lightpaths.txt"
    echo "  [2/2] Simulator done"
  fi

  # Generate plots (always regenerate)
  local PLOT_DIR="$RUN_DIR/plots"
  mkdir -p "$PLOT_DIR"

  echo "  Generating alarm flow plots..."
  $PYTHON "$SIM_DIR/plot_alarm_flow_synthetic.py" \
    --alarm-flow "$RUN_DIR/alarm_flow.csv" \
    --outdir "$PLOT_DIR" 2>/dev/null || echo "    (alarm flow plot failed)"

  echo "  Generating BBE/BBER/ES plots..."
  $PYTHON "$SIM_DIR/plot_bbe_lat_bber_es.py" \
    --failure "$RUN_DIR/failure.csv" \
    --topology "$TOPO_YAML" \
    --data-dir "$DATA_DIR" \
    --outdir "$PLOT_DIR" \
    --boards-from-alarm-flow "$RUN_DIR/alarm_flow.csv" \
    --affected-all 2>/dev/null || echo "    (BBE plot failed)"

  local NPLOTS
  NPLOTS=$(ls "$PLOT_DIR"/*.png 2>/dev/null | wc -l | tr -d ' ')
  echo "  Done: $MODE / $EVENT -> $NPLOTS plot files"
}

# ── NOREGEN failures ──────────────────────────────────────────────────────
echo ""
echo "========================================================================"
echo "  NOREGEN WORKFLOW"
echo "========================================================================"

# Fiber failures: OA relay board
run_event noregen "Fiber_Cut"       'ROADM0-OA002$0'   "RELAY" "Critical"
run_event noregen "Fiber_Crack"     'ROADM0-OA002$0'   "RELAY" "Critical"
run_event noregen "Fiber_Aging"     'ROADM0-OA002$0'   "RELAY" "Critical"

# Line/XCON failures: creation boards
run_event noregen "Line_Disconnect"      'ROADM0-Line025$0'  "SRC" "Critical"
run_event noregen "XCON_Port_Down"       'ROADM0-XCON025$0'  "SRC" "Critical"
run_event noregen "XCON_Fabric_Fault"    'ROADM0-XCON025$0'  "SRC" "Critical"
run_event noregen "XCON_Buffer_Overflow" 'ROADM0-XCON025$0'  "SRC" "Critical"

# Tributary failure: termination board
run_event noregen "Tributary_Port_Down"  'ROADM1-Tributary051$0' "TERMINATION" "Critical"

# ── REGEN failures ────────────────────────────────────────────────────────
echo ""
echo "========================================================================"
echo "  REGEN WORKFLOW"
echo "========================================================================"

# Fiber failures: OA relay board (transmit chain, before regen at span boundary)
run_event regen "Fiber_Cut"       'ROADM0-OA002$0'   "RELAY" "Critical"
run_event regen "Fiber_Crack"     'ROADM0-OA002$0'   "RELAY" "Critical"
run_event regen "Fiber_Aging"     'ROADM0-OA002$0'   "RELAY" "Critical"

# Line/XCON failures: creation boards (from regen topology path 1)
run_event regen "Line_Disconnect"      'ROADM0-Line067$0'  "SRC" "Critical"
run_event regen "XCON_Port_Down"       'ROADM0-XCON067$0'  "SRC" "Critical"
run_event regen "XCON_Fabric_Fault"    'ROADM0-XCON067$0'  "SRC" "Critical"
run_event regen "XCON_Buffer_Overflow" 'ROADM0-XCON067$0'  "SRC" "Critical"

# Tributary failure: termination board (from regen topology path 1)
run_event regen "Tributary_Port_Down"  'ROADM1-Tributary012$0' "TERMINATION" "Critical"

# ── Step 4: Comparison report ─────────────────────────────────────────────
echo ""
echo "============================================"
echo "  Generating comparison report..."
echo "============================================"
$PYTHON "$SIM_DIR/report_regen_vs_noregen.py" \
  > "$SIM_DIR/outputs/reports/regen_vs_noregen_comparison.txt"

# ── Summary ───────────────────────────────────────────────────────────────
echo ""
echo "========================================================================"
echo "  ALL WORKFLOWS COMPLETE"
echo "========================================================================"
echo ""
echo "  Noregen outputs: $NR_BASE/"
echo "    Topology:    topology_graph.png"
echo "    Failures:    Fiber_Cut/ Fiber_Crack/ Fiber_Aging/ Line_Disconnect/"
echo "                 XCON_Port_Down/ XCON_Fabric_Fault/ XCON_Buffer_Overflow/"
echo "                 Tributary_Port_Down/"
echo "    Each has:    failure.csv, alarm_flow.csv, plots/"
echo ""
echo "  Regen outputs:   $RG_BASE/"
echo "    Topology:    topology_graph.png"
echo "    Failures:    (same 8 types as above)"
echo "    Each has:    failure.csv, alarm_flow.csv, plots/"
echo ""
echo "  Reports: $SIM_DIR/outputs/reports/"
echo "    regen_vs_noregen_comparison.txt"
echo "    summary_comparison.csv"
echo "    alarm_distribution.csv"
echo "    detailed_alarm_flows.csv"
echo ""
echo "  Total plot files:"
echo "    Noregen: $(find "$NR_BASE" -name '*.png' 2>/dev/null | wc -l | tr -d ' ')"
echo "    Regen:   $(find "$RG_BASE" -name '*.png' 2>/dev/null | wc -l | tr -d ' ')"
